"""empty message

Revision ID: 9aca66bd439f
Revises: 2d1ba2ba5553
Create Date: 2021-01-09 18:35:17.012490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aca66bd439f'
down_revision = '2d1ba2ba5553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_facebook_link_key', 'artist', type_='unique')
    op.drop_constraint('artist_image_link_key', 'artist', type_='unique')
    op.drop_constraint('artist_website_key', 'artist', type_='unique')
    op.drop_constraint('venue_facebook_link_key', 'venue', type_='unique')
    op.drop_constraint('venue_image_link_key', 'venue', type_='unique')
    op.drop_constraint('venue_website_key', 'venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('venue_website_key', 'venue', ['website'])
    op.create_unique_constraint('venue_image_link_key', 'venue', ['image_link'])
    op.create_unique_constraint('venue_facebook_link_key', 'venue', ['facebook_link'])
    op.create_unique_constraint('artist_website_key', 'artist', ['website'])
    op.create_unique_constraint('artist_image_link_key', 'artist', ['image_link'])
    op.create_unique_constraint('artist_facebook_link_key', 'artist', ['facebook_link'])
    # ### end Alembic commands ###
